parserOptions:
  ecmaVersion: 6
  sourceType: module
env:
  node: true
  browser: true
extends:
  - 'airbnb-base'
rules:
  object-shorthand: 0
  func-names: 0
  space-before-function-paren: 0
  no-var: 0
  prefer-arrow-callback: 0
  comma-dangle: 1
  prefer-destructuring: 0
  object-curly-newline: 1
  no-underscore-dangle: 0

# root: true